# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'OneTenDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OneTenDemo
pod 'SigmobAd-iOS'
pod 'GDTMobSDK'
pod 'BaiduMobAdSDK'
pod 'KSAdSDK'
pod "VungleAds"
pod 'Ads-Global'
#pod 'Google-Mobile-Ads-SDK'
#pod 'IronSourceSDK'
pod 'ChartboostSDK'
pod 'Fyber_Marketplace_SDK'
pod 'StartAppSDK'
pod 'myTargetSDK'
pod 'AnyThinkiOS'
pod 'BigoADS'
pod 'TianmuSDK'
pod 'YandexMobileAds'
pod 'Ads-Fusion-CN-Beta', '5.1.7.0' , :subspecs => [
    'Ads-CSJ',
    'CSJMediation'
  ]

pod 'MintegralAdSDK/BidNativeAd'
pod 'MintegralAdSDK/BidRewardVideoAd'
pod 'MintegralAdSDK/CNAddition'
pod 'MintegralAdSDK/BidSplashAd'

end
